version: '3.7'
services:
  go-api:
    build: 
      context: .
      dockerfile: docker/alpine/Dockerfile
    container_name: go-skeleton
    platform: linux/arm64
    env_file:
      - .env
    ports:
      - 8080:8080

networks:
    default:
        name: go-skeleton-network
