version: '3.7'
services:
  go-api:
    build: 
      context: .
      dockerfile: docker/alpine/Dockerfile
    container_name: go-skeleton
    platform: linux/arm64
    env_file:
      - .env
    ports:
      - 1323:1323

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: skeleton
    ports:
        - "3306:3306"
    volumes:
        - ./storage/mysql:/var/lib/mysql

networks:
    default:
        name: go-skeleton-network
